version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    docker:
      - image: circleci/node:16.13.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test
      - run: yarn test:cov
      - run: yarn test:e2e

  deploy:
    docker:
      - image: circleci/node:16.13.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker build -t makifdb/atolye15-demo:lasest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push makifdb/atolye15-demo

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
