# ~/.circleci/config.yml

version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16.13.2
    parallelism: 4

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test
      - run: yarn test:cov
      - run: yarn test:e2e

  build-stage:
    machine: true
    steps:
      - checkout
      - run: docker build --target builder -t makifdb/atolye15-demo:lasest .
      - run: docker build --target installer -t makifdb/atolye15-demo:lasest .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push makifdb/atolye15-demo

  build-production:
    machine: true
    steps:
      - checkout
      - run: docker build -t makifdb/atolye15-demo:produciton .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push makifdb/atolye15-demo

workflows:
  version: 2
  test-build-production:
    jobs:
      - test
      - build-stage:
          requires:
            - test
          filters:
            branches:
              only: develop
      - build-production:
          requires:
            - test
          filters:
            branches:
              only: master
